format_version: 2
environments:
  ci:
    pipelines:
      - "team11API"
      
pipelines:
  "team11API":
    group: team11
    materials:
      ui:
        git: "git@github.com:pajmera4/bootcamp-just-cinemas-api"
    stages:
      - buildAndTest:
          jobs:
            test:
              resources:
                - node-and-java
              tasks:
                - script: |
                    buildAndDeploy/build/build.sh team11

      - deploy:
           jobs:
            deploy:
              resources:
                - node-and-java
              tasks:
                - script: |
                    buildAndDeploy/deploy/deploy.sh team11 akshay-key-pair
